kind: Service
apiVersion: v1
metadata:
  name: helidonLearning
  labels:
    app: helidonLearning
spec:
  type: ClusterIP
  selector:
    app: helidonLearning
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidonLearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidonLearning
  template:
    metadata:
      labels:
        app: helidonLearning
        version: v1
    spec:
      containers:
      - name: helidonLearning
        image: helidonLearning
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
